name: Debug
'on':
  pull_request_target:
    branches: prod-br-01 
jobs:
  debug:
    runs-on:
    - self-hosted
    - Linux
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: debug test
      run: bash start.sh

